Fiap.RH.Sistema.Contratacao.MCV.Web/ViewModels/HabilidadeViewModel.cs
using Fiap.RH.Sistema.Contratacao.Dominio;
using System.Collections.Generic;

namespace Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels
{
    public class HabilidadeViewModel
    {
        #region VIEW PROPS
        public string Mensagem { get; set; }
        #endregion

        #region MODEL PROPS
        public int Id { get; set; }

        public string Nome { get; set; }
        #endregion

        #region MODEL COLLECTION
        public ICollection<Habilidade> Habilidades { get; set; }
        #endregion
    }
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Controllers/HabilidadeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Fiap.RH.Sistema.Contratacao.Persistencia.UnitsOfWork;
using Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels;
using Fiap.RH.Sistema.Contratacao.Dominio;


namespace Fiap.RH.Sistema.Contratacao.MCV.Web.Controllers
{
    public class HabilidadeController : Controller
    {
        #region FIELDS
        private UnitOfWork _unit = new UnitOfWork();
        #endregion


        #region GET
        [HttpGet]
        public ActionResult Cadastrar(string mensagem)
        {
            var habilidadeViewModel = new HabilidadeViewModel()
            {
                Mensagem = mensagem
            };
            return View(habilidadeViewModel);
        }

        [HttpGet]
        public ActionResult Listar()
        {
            var habilidadeViewModel = new HabilidadeViewModel();
            try
            {
                habilidadeViewModel.Habilidades = _unit.HabilidadeRepository.Listar();
            }
            catch (Exception e)
            {
                habilidadeViewModel.Mensagem = "Erro ao buscar as habilidades no banco de dados: " + e.Message;
            }
            return View(habilidadeViewModel);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            Habilidade habilidade = null;
            var habilidadeViewModel = new HabilidadeViewModel();

            try
            {
                habilidade = _unit.HabilidadeRepository.BuscarPorId(id);
                habilidadeViewModel.Id = habilidade.Id;
                habilidadeViewModel.Nome = habilidade.Nome;
            }
            catch (Exception e)
            {
                habilidadeViewModel.Mensagem = "Erro ao buscar a habilidade no banco de dados para editar: " + e.Message;
            }

            return View(habilidadeViewModel);
        }
        #endregion


        #region POST
        [HttpPost]
        public ActionResult Cadastrar(HabilidadeViewModel habilidadeViewModel)
        {
            if (ModelState.IsValid)
            {
               try
               {
                    if (IsHabilidadeDuplicada(habilidadeViewModel))
                    {
                        habilidadeViewModel.Mensagem = "Já existe uma habilidade com este nome!";
                        return View(habilidadeViewModel);
                    }

                    var habilidade = new Habilidade()
                    {
                        Nome = habilidadeViewModel.Nome
                    };

                    _unit.HabilidadeRepository.Cadastrar(habilidade);
                    _unit.Save();
               }
               catch (Exception e)
               {
                    habilidadeViewModel.Mensagem = "Erro ao cadastrar habilidade: " + e.Message;
                    return View(habilidadeViewModel);
               }
            }
            else return View(habilidadeViewModel);

            return RedirectToAction("Listar");
        }

        [HttpPost]
        public JsonResult Remover(int id)
        {
            try
            {
                _unit.HabilidadeRepository.Remover(id);
                _unit.Save();
            }
            catch (Exception e)
            {
                return Json(new
                {
                    status = false,
                    mensagem = "Existe algum relatório de candidato associado a esta habilidade?"
                               + " Se sim deve trocar antes de remover."
                               + " Erro ao remover: " + e.Message
                });
            }
            return Json(new { status = true });
        }

        [HttpPost]
        public ActionResult Editar(HabilidadeViewModel habilidadeViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (IsHabilidadeDuplicada(habilidadeViewModel))
                    {
                        habilidadeViewModel.Mensagem = "Já existe uma habilidade com este nome!";
                        return View(habilidadeViewModel);
                    }

                    var habilidade = _unit.HabilidadeRepository.BuscarPorId(habilidadeViewModel.Id);
                    habilidade.Nome = habilidadeViewModel.Nome;
                    _unit.HabilidadeRepository.Editar(habilidade);
                    _unit.Save();
                }
                catch (Exception e)
                {
                    habilidadeViewModel.Mensagem = "Erro ao editar a habilidade: " + e.Message;
                    return View(habilidadeViewModel);
                }
            }
            else return View(habilidadeViewModel);

            return RedirectToAction("Listar");
        }
        #endregion


        #region PRIVATE
        public bool IsHabilidadeDuplicada(HabilidadeViewModel habilidadeViewModel)
        {
            var habilidades = _unit.HabilidadeRepository.BuscarPor(a => a.Nome == habilidadeViewModel.Nome);
            if (habilidades.Any() && !(habilidades.First().Id == habilidadeViewModel.Id)) return true;
            return false;
        }
        #endregion


        #region OVERRIDE
        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
        #endregion
    }
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Habilidade/Cadastrar.cshtml
@model Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels.HabilidadeViewModel

@{
    ViewBag.Title = "Cadastrar Habilidade";
    ViewBag.TitleMenu = "Habilidades";
}

<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h2>Cadastrar Habilidade</h2>
        </div>
        <div class="card-body">

            @Helper.Message(Model.Mensagem, "alert alert-warning")

            @using (Html.BeginForm("Cadastrar", "Habilidade", FormMethod.Post, new { @class = "form form-horizontal", id = "formularioHabilidade" }))
            {<div class="row">
                <div class="col-md-6">
                    @Html.Partial("_formulario", Model)
                </div>
            </div>
                    <div class="row">

                        <div class="col-md-6" style="margin-top: 25px;">
                            @Helper.Submit("Adicionar", "btn btn-success")
                        </div>
                    </div>
            }
        </div>
    </div>
</div>
            

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Habilidade/Editar.cshtml
@model Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels.HabilidadeViewModel

@{
    ViewBag.Title = "Editar Habilidades";
    ViewBag.TitleMenu = "Habilidades";
}

<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h2>Cadastrar Habilidade</h2>
        </div>
        <div class="card-body">

            @Helper.Message(Model.Mensagem, "alert alert-warning")

            @using (Html.BeginForm("Editar", "Habilidade", FormMethod.Post, new { @class = "form form-horizontal", id = "formularioHabilidade" }))
            {
                @Html.HiddenFor(h => h.Id)
                <div class="row">
                    <div class="col-md-6">
                        @Html.Partial("_formulario", Model)
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-6" style="margin-top: 25px;">
                        @Helper.Submit("Concluir", "btn btn-success")
                    </div>
                </div>
            }
        </div>
    </div>
</div>
            

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Habilidade/Listar.cshtml
@model Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels.HabilidadeViewModel

@{
    ViewBag.Title = "Listar Habilidades";
    ViewBag.TitleMenu = "Habilidades";
}

<div class="col-xs-12">
    <div class="card">
        <div class="card-header" style="padding: 10px 20px; flex-direction: column;">
            <span style="font-size: 28px;">Fábricas</span>
            <!--ActionLink para cadastrar fábricas-->
            @Html.ActionLink("Cadastrar Habilidade", "Cadastrar", "Habilidade", new { @class = "btn btn-xs btn-primary" })
        </div>


        @Helper.Message(Model.Mensagem, "alert alert-warning")

        <table class="datatable table table-striped primary" cellspacing="0" width="100%" id="HabilidadeTable">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var habilidade in Model.Habilidades)
                {
                    <tr id="@habilidade.Id">
                        <td>@habilidade.Nome</td>
                        <td>
                            <a class="btn btn-info btn-xs" href="/Habilidade/Editar/@habilidade.Id"><i class="fa fa-pencil"></i></a>
                            <a onclick="removePeloId(@habilidade.Id)" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/ViewModels/habilidade.js"></script>
    <script>
        $(document).ready(function () {
            var oTable = $('#HabilidadeTable').dataTable({
                "aoColumnDefs": [
                { "bSortable": false, "aTargets": [0] }
                ],
                "aaSorting": [[1, 'asc']],
                "dom": '<"top"fl>rt<"bottom"ip><"clear">',
                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ resultados por página",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Pesquisar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        })
    </script>
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Habilidade/_formulario.cshtml
@model Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels.HabilidadeViewModel

@Html.LabelFor(h => h.Nome)
@Html.TextBoxFor(h => h.Nome, new { @class="form-control"})