Fiap.RH.Sistema.Contratacao.MCV.Web/ViewModels/FabricaViewModel.cs
using Fiap.RH.Sistema.Contratacao.Dominio;
using System.Collections.Generic;

namespace Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels
{
    public class FabricaViewModel
    {
        #region VIEW PROPS
        public string Mensagem { get; set; }
        #endregion

        #region VIEW ESTATISTICAS
        public int Inscritos { get; set; }
        public decimal MediaGeral { get; set; }
        public IDictionary<string, int> Participantes { get; set; }
        public IDictionary<string, int> Publico { get; set; }
        public IDictionary<string, int> Presentes { get; set; }
        public IDictionary<string, int> Aprovados { get; set; }
        public IDictionary<string, int> AprovadosXCursos { get; set; }
        #endregion

        #region MODEL PROPS 
        public int Id { get; set; }
        public string Nome { get; set; }
        public decimal NotaCorte { get; set; }
        #endregion

        #region MODEL COLLECTIONS
        public ICollection<Aula> Aulas { get; set; }
        public ICollection<Fabrica> Fabricas { get; set; }
        #endregion
    }
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Controllers/FabricaController.cs
using Fiap.RH.Sistema.Contratacao.Dominio;
using Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels;
using Fiap.RH.Sistema.Contratacao.Persistencia.UnitsOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Fiap.RH.Sistema.Contratacao.MCV.Web.Controllers
{
    public class FabricaController : Controller
    {
        #region FIELDS
        private UnitOfWork _unit = new UnitOfWork();
        #endregion


        #region GET
        [HttpGet]
        public ActionResult Cadastrar(string mensagem)
        {
            var fabricaViewModel = new FabricaViewModel()
            {
                Mensagem = mensagem
            };
            return View(fabricaViewModel);
        }

        [HttpGet]
        public ActionResult Listar()
        {
            var fabricaViewModel = new FabricaViewModel();
            try
            {
                fabricaViewModel.Fabricas = _unit.FabricaRepository.Listar();
            }
            catch (Exception e)
            {
                fabricaViewModel.Mensagem = "Erro ao buscar as fabricas no banco de dados: " + e.Message;
            }
            return View(fabricaViewModel);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            var fabricaViewModel = new FabricaViewModel();
            Fabrica fabrica = null;
            try
            {
                fabrica = _unit.FabricaRepository.BuscarPorId(id);
                fabricaViewModel.Nome = fabrica.Nome;
                fabricaViewModel.NotaCorte = fabrica.NotaCorte;
                fabricaViewModel.Id = id;
            }
            catch (Exception e)
            {
                fabricaViewModel.Mensagem = "Erro ao buscar a fabrica no banco de dados para editar: " + e.Message;
            }

            return View(fabricaViewModel);
        }

        [HttpGet]
        public ActionResult VerEstatisticas(int id)
        {
            ICollection<Candidato> candidatos = null;
            FabricaViewModel fabricaViewModel = new FabricaViewModel();

            try
            {
                candidatos = _unit.CandidatoRepository.BuscarPor(c => c.IdFabrica == id);
                var fabrica = _unit.FabricaRepository.BuscarPorId(id);
                fabricaViewModel.Nome = fabrica.Nome;
                fabricaViewModel.NotaCorte = fabrica.NotaCorte;
                GerarEstatisticas(candidatos, fabricaViewModel);
            }
            catch (Exception e)
            {
                fabricaViewModel.Mensagem = "Erro ao gerar as estatisticas da Fabrica selecionada: " + e.Message;
            }
            
            return View(fabricaViewModel);
        }
        #endregion


        #region POST
        [HttpPost]
        public ActionResult Cadastrar(FabricaViewModel fabricaViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if(IsFabricaDuplicada(fabricaViewModel))
                    {
                        fabricaViewModel.Mensagem = "Já existe uma fabrica com este nome!";
                        return View(fabricaViewModel);
                    }

                    var fabrica = new Fabrica()
                    {
                        Nome = fabricaViewModel.Nome,
                        NotaCorte = fabricaViewModel.NotaCorte
                    };

                    _unit.FabricaRepository.Cadastrar(fabrica);
                    _unit.Save();
                }
                catch (Exception e)
                {
                    fabricaViewModel.Mensagem = "Erro ao cadastrar fabrica: " + e.Message;
                    return View(fabricaViewModel);
                }

            }
            else return View(fabricaViewModel);

            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult Editar(FabricaViewModel fabricaViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (IsFabricaDuplicada(fabricaViewModel))
                    {
                        fabricaViewModel.Mensagem = "Já existe uma fabrica com este nome!";
                        return View(fabricaViewModel);
                    }

                    var fabrica = _unit.FabricaRepository.BuscarPorId(fabricaViewModel.Id);
                    fabrica.Id = fabricaViewModel.Id;
                    fabrica.Nome = fabricaViewModel.Nome;

                    if(fabrica.NotaCorte != fabricaViewModel.NotaCorte)
                        CandidatoController.RevalidaAprovacoes(fabricaViewModel.NotaCorte, _unit);

                    _unit.FabricaRepository.Editar(fabrica);
                    _unit.Save();
                }
                catch (Exception e)
                {
                    fabricaViewModel.Mensagem = "Erro ao editar fabrica: " + e.Message;
                    return View(fabricaViewModel);
                }
            }
            else return View(fabricaViewModel);

            return RedirectToAction("Listar");
        }
        #endregion


        #region STATIC
        public static bool IsCandidatoAprovado(decimal notaCandidato, int idFabrica, UnitOfWork unit)
        {
            Fabrica fabrica = null;
            try
            {
                fabrica = unit.FabricaRepository.BuscarPorId(idFabrica);
            }
            catch (Exception e)
            {
                throw new Exception("Erro ao buscar a fábrica no banco de dados para recuperar a nota de corte: " + e.Message);
            }

            if (notaCandidato >= fabrica.NotaCorte) return true;
            else return false;
        }
        #endregion


        #region PRIVATE
        private bool IsFabricaDuplicada(FabricaViewModel fabricaViewModel)
        {
            var fabricas = _unit.FabricaRepository.BuscarPor(f => f.Nome == fabricaViewModel.Nome);
            if (fabricas.Any() && !(fabricas.First().Id == fabricaViewModel.Id)) return true;
            return false;
        }

        private FabricaViewModel GerarEstatisticas(ICollection<Candidato> candidatos, FabricaViewModel f)
        {
            // Inilicializadores
            f.Participantes = new Dictionary<string, int>();
            f.Publico = new Dictionary<string, int>();
            f.Presentes = new Dictionary<string, int>();
            f.Aprovados = new Dictionary<string, int>();
            f.AprovadosXCursos = new Dictionary<string, int>();
            f.Aprovados.Add("Aprovados", 0);
            f.Aprovados.Add("Reprovados", 0);
            f.Inscritos = candidatos.Count;
            f.Presentes.Add("Presentes", 0);
            f.Presentes.Add("Ausentes", 0);
            f.Publico.Add("Masculino", 0);
            f.Publico.Add("Feminino", 0);
            List<decimal> notas = new List<decimal>();

            // Calcula cada candidato
            foreach (Candidato c in candidatos)
            {
                if (c.ProvaTecnica == true && c.Nota > 0)
                {
                    //adiciona presentes e suas notas
                    f.Presentes["Presentes"]++;
                    notas.Add((decimal)c.Nota);

                    // Aprovado ou reprovado? Se true adiciona em Aprovados X Curso, sem duplicar o curso no Map (dictionary)
                    if (c.Aprovado == true)
                    {
                        f.Aprovados["Aprovados"]++;
                        if(f.AprovadosXCursos.ContainsKey(c.Curso.Nome)) f.AprovadosXCursos[c.Curso.Nome]++;
                        else f.AprovadosXCursos.Add(c.Curso.Nome, 1);
                    }
                    else f.Aprovados["Reprovados"]++;
                }
                // se nao fez a prova tecnica estava ausente
                else f.Presentes["Ausentes"]++;

                // Adiciona participante sem duplicar o curso no Map (dictionary)
                if(f.Participantes.ContainsKey(c.Curso.Nome)) f.Participantes[c.Curso.Nome]++;
                else f.Participantes.Add(c.Curso.Nome, 1);

                // Adiciona como Feminino ou Masculino true = Masculino
                if (c.Publico == true) f.Publico["Masculino"]++;
                else f.Publico["Feminino"]++;
            }

            // Calcula Media Geral
            var soma = 0m;
            notas.ForEach(n => soma += n);
            f.MediaGeral = soma / notas.Count;

            // Retorna View Model populado
            return f;
        }
        #endregion


        #region OVERRIDE
        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
        #endregion
    }
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Fabrica/Cadastrar.cshtml
@model Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels.FabricaViewModel

@{
    ViewBag.Title = "Cadastrar Fábrica";
    ViewBag.TitleMenu = "Fábrica";
}

<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h2>Cadastrar Fábrica</h2>
        </div>
        <div class="card-body">


            @Helper.Message(Model.Mensagem, "alert alert-warning")

            @using (Html.BeginForm("Cadastrar", "Fabrica", FormMethod.Post, new { @class = "form form-horizontal", id = "formularioFabrica" }))
            {
                <div class="row">
                    <div class="col-md-6">
                        @Html.Partial("_formulario", Model)
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-6" style="margin-top: 25px;">
                        @Helper.Submit("Adicionar", "btn btn-success")
                    </div>
                </div>
            }

        </div>
    </div>
</div>

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Fabrica/Editar.cshtml
@model Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels.FabricaViewModel

@{
    ViewBag.Title = "Editar Fábrica";
    ViewBag.TitleMenu = "Fábrica";
}

<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h2>Cadastrar Fábrica</h2>
        </div>
        <div class="card-body">

            @Helper.Message(Model.Mensagem, "alert alert-warning")

            @Helper.Message("Aviso: mudar a nota de corte remove relatórios individuais e avaliações comportamentais dos reprovados, bem como a chamada das aulas!", "alert alert-danger")

            @using (Html.BeginForm("Editar", "Fabrica", FormMethod.Post, new { @class = "form form-horizontal", id = "formularioFabrica" }))
            {
                @Html.HiddenFor(f => f.Id)
                <div class="row">
                    <div class="col-md-6">
                        @Html.Partial("_formulario", Model)
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-6" style="margin-top: 25px;">
                        @Helper.Submit("Concluir", "btn btn-success")
                    </div>
                </div>
            }

        </div>
    </div>
</div>
            

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Fabrica/Listar.cshtml
@model Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels.FabricaViewModel

@{
    ViewBag.Title = "Listar Fábricas";
    ViewBag.TitleMenu = "Fábrica";
}

<div class="col-xs-12">
    <div class="card">
        <div class="card-header" style="padding: 10px 20px; flex-direction: column;">
            <span style="font-size: 28px;">Fábricas</span>
            <!--ActionLink para cadastrar fábricas-->
            @Html.ActionLink("Cadastrar Fábrica", "Cadastrar", "Fabrica", new { @class = "btn btn-xs btn-primary" })
        </div>
        <div class="card-body no-padding">

            @Helper.Message(Model.Mensagem, "alert alert-warning")
            <table class="datatable table table-striped primary" cellspacing="0" width="100%" id="FabricaTable">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Nota de Corte</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var fabrica in Model.Fabricas)
                    {
                        <tr>
                            <td>@fabrica.Nome</td>
                            <td>@fabrica.NotaCorte</td>
                            <td>
                                <a href="/Fabrica/VerEstatisticas/@fabrica.Id" class="btn btn-info btn-xs"><i class="fa fa-bar-chart"></i></a>
                                <a href="/Fabrica/Editar/@fabrica.Id" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    @section scripts
{
        <script>
            $(document).ready(function () {
                var oTable = $('#FabricaTable').dataTable({
                    "aoColumnDefs": [
                    { "bSortable": false, "aTargets": [0] }
                    ],
                    "aaSorting": [[1, 'asc']],
                    "dom": '<"top"fl>rt<"bottom"ip><"clear">',
                    "language": {
                        "sEmptyTable": "Nenhum registro encontrado",
                        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                        "sInfoPostFix": "",
                        "sInfoThousands": ".",
                        "sLengthMenu": "_MENU_ resultados por página",
                        "sLoadingRecords": "Carregando...",
                        "sProcessing": "Processando...",
                        "sZeroRecords": "Nenhum registro encontrado",
                        "sSearch": "Pesquisar",
                        "oPaginate": {
                            "sNext": "Próximo",
                            "sPrevious": "Anterior",
                            "sFirst": "Primeiro",
                            "sLast": "Último"
                        },
                        "oAria": {
                            "sSortAscending": ": Ordenar colunas de forma ascendente",
                            "sSortDescending": ": Ordenar colunas de forma descendente"
                        }
                    }
                });
            })
        </script>
    }

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Fabrica/VerEstatisticas.cshtml
@model Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels.FabricaViewModel

@{
    ViewBag.Title = "Estatísticas";
    ViewBag.TitleMenu = "Fábrica";
}

<!--ADICIONAR BOTÃO DE IMPRESSÃO-->
<div class="col-xs-12">
    <div class="card">
        <div class="card-header" style="padding: 10px 20px; flex-direction: row; display: flex; justify-content: space-between; align-items: flex-end;">
            <h2>Estatísticas</h2>
            <button type="button" class="btn btn-primary btn-xs" style="margin-bottom: 10px;" onclick="window.print();" id="Printbutton">Imprimir</button>
        </div>
        <div class="card-body">
            <h3>Estatisticas @Model.Nome</h3>
        </div>
    </div>
</div>

<!--Banners de Informações-->
<div class="row">
    <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
        <a class="card card-banner card-green-light">
            <div class="card-body">
                <i class="icon fa fa-group fa-4x"></i>
                <div class="content">
                    <div class="title">Inscritos</div>
                    <div class="value"><span class="sign"></span>@Model.Inscritos</div>
                </div>
            </div>
        </a>

    </div>
    <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
        <a class="card card-banner card-blue-light">
            <div class="card-body">
                <i class="icon fa fa-check fa-4x"></i>
                <div class="content">
                    <div class="title">Aprovados</div>
                    <div class="value"><span class="sign"></span>@Model.Aprovados.First().Value</div>
                </div>
            </div>
        </a>

    </div>
    <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
        <a class="card card-banner card-yellow-light">
            <div class="card-body">
                <i class="icon fa fa-graduation-cap fa-4x"></i>
                <div class="content">
                    <div class="title">Média Geral</div>
                    <div class="value"><span class="sign"></span>@Model.MediaGeral.ToString("F1")</div>
                </div>
            </div>
        </a>

    </div>
    <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
        <a class="card card-banner card-green-light">
            <div class="card-body">
                <i class="icon fa fa-certificate fa-4x"></i>
                <div class="content">
                    <div class="title">Nota de Corte</div>
                    <div class="value"><span class="sign"></span>@Model.NotaCorte.ToString("F1")</div>
                </div>
            </div>
        </a>

    </div>
</div>

<!--Gráfico 1 - Participantes-->
<div class="row row-estatistica">
    <!--Tabela do Gráfico-->
    <div class="col-md-5">
        <div class="card">

            <table class="table table-striped" id="participantes">
                <thead>
                    <tr>
                        <th>Participantes</th>
                        <th>Qts</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var p in Model.Participantes)
                    {
                        <tr>
                            <td>@p.Key</td>
                            <td class="qtd">@p.Value</td>
                        </tr>
                    }
                    <tr>
                        <td><b>Total</b></td>
                        <td class="total"></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <!--Gráfico-->
    <div class="col-md-7 div-grafico">
        <div class="card">
            <div class="div-grafico-display" id="participantes-grafico"></div>
        </div>
    </div>
</div>

<!--Gráfico 2 - Público Alvo-->
<div class="row row-estatistica">
    <!--Tabela do Gráfico-->
    <div class="col-md-5">
        <div class="card">

            <table class="table table-striped" id="publico">
                <thead>
                    <tr>
                        <th>Público Alvo</th>
                        <th>Qts</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var p in Model.Publico)
                    {
                        <tr>
                            <td>@p.Key</td>
                            <td class="qtd">@p.Value</td>
                        </tr>
                    }
                    <tr>
                        <td><b>Total</b></td>
                        <td class="total"></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <!--Gráfico-->
    <div class="col-md-7 div-grafico">
        <div class="card">
            <div class="div-grafico-display" id="publico-grafico"></div>
        </div>
    </div>
</div>

<!--Gráfico 3 - Presentes X Ausentes-->
<div class="row row-estatistica">
    <!--Tabela do Gráfico-->
    <div class="col-md-5">
        <div class="card">

            <table class="table table-striped" id="presentes">
                <thead>
                    <tr>
                        <th>Presentes X Ausentes</th>
                        <th>Qts</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var p in Model.Presentes)
                    {
                        <tr>
                            <td>@p.Key</td>
                            <td class="qtd">@p.Value</td>
                        </tr>
                    }
                    <tr>
                        <td><b>Total</b></td>
                        <td class="total"></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <!--Gráfico-->
    <div class="col-md-7 div-grafico">
        <div class="card">
            <div class="div-grafico-display" id="presentes-grafico"></div>
        </div>
    </div>
</div>

<!--Gráfico 4 - Aprovados X Reprovados-->
<div class="row row-estatistica">
    <!--Tabela do Gráfico-->
    <div class="col-md-5">
        <div class="card">

            <table class="table table-striped" id="aprovados">
                <thead>
                    <tr>
                        <th>Aprovados X Reprovados</th>
                        <th>Qts</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var p in Model.Aprovados)
                    {
                        <tr>
                            <td>@p.Key</td>
                            <td class="qtd">@p.Value</td>
                        </tr>
                    }
                    <tr>
                        <td><b>Total</b></td>
                        <td class="total"></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <!--Gráfico-->
    <div class="col-md-7 div-grafico">
        <div class="card">
            <div class="div-grafico-display" id="aprovados-grafico"></div>
        </div>
    </div>
</div>

<!--Gráfico 5 - Participantes X Aprovados-->
<div class="row row-estatistica">
    <!--Tabela do Gráfico-->
    <div class="col-md-5">
        <div class="card">

            <table class="table table-striped" id="participantes-aprovados">
                <thead>
                    <tr>
                        <th>Participantes Aprovados X Curso</th>
                        <th>Qts</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var p in Model.AprovadosXCursos)
                    {
                        <tr>
                            <td>@p.Key</td>
                            <td class="qtd">@p.Value</td>
                        </tr>
                    }
                    <tr>
                        <td><b>Total</b></td>
                        <td class="total"></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <!--Gráfico-->
    <div class="col-md-7 div-grafico">
        <div class="card">
            <div class="div-grafico-display" id="participantes-aprovados-grafico"></div>
        </div>
    </div>
</div>

@section scripts
    {
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.12/datatables.min.js"></script>

    <script>

        function drawChart() {
            $('table').each(function (index) {
                var col1 = $(this).find('th:nth-child(1)').html();
                var col2 = $(this).find('th:nth-child(2)').html();
                var tabela = this;
                var total = 0;

                // Carregar no gráfico
                var data = new google.visualization.DataTable();
                data.addColumn('string', col1);
                data.addColumn('number', col2);

                $(tabela).find('td[class=qtd]').each(function () {
                    var valueText = $(this).closest('tr').find('td:first').text();
                    var valueQtd = parseInt($(this).html());
                    data.addRow([valueText, valueQtd]);
                    total += valueQtd;
                });

                $("<b>" + total + "</b>").appendTo($(tabela).find("td[class=total]"));
                var title = $(tabela).find('thead > tr > th:first').text();
                var options = {
                    'title': title,
                    'width': 680,
                    'height': 300,
                    'colors': ['#ED145D', '#000', '#fc2a70', '#d8044b', '#5e5e5e']
                };
                var container = $(tabela).closest('.card').closest('.row').find('.div-grafico').find('.div-grafico-display').attr('id');
                var chart = new google.visualization.PieChart(document.getElementById(container));
                chart.draw(data, options);

            });
        };


        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);



    </script>

    <!-- Thiago -->
    <script src="~/Scripts/Graficos/datatables.min.js"></script>
    <script src="~/Scripts/Graficos/loader.js"></script>    
    <script src="~/Scripts/Graficos/jsapi.js"></script>
    <script src="~/Scripts/Graficos/graficos.js"></script>
    <script src="~/Scripts/ViewModels/fabrica.js"></script>
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Fabrica/_formulario.cshtml
@model Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels.FabricaViewModel

@Html.LabelFor(f => f.Nome)
@Html.TextBoxFor(f => f.Nome, new { @class = "form-control" })

@Html.LabelFor(f => f.NotaCorte)
@Html.TextBoxFor(f => f.NotaCorte, new { @class = "form-control" })