Fiap.RH.Sistema.Contratacao.MCV.Web/Controllers/AulaController.cs
using Fiap.RH.Sistema.Contratacao.Persistencia.UnitsOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.RH.Sistema.Contratacao.MCV.Web.Controllers
{
    public class AulaController : Controller
    {
        #region FIELDS
        private UnitOfWork _unit = new UnitOfWork();
        #endregion

        // GET: Aula
        public ActionResult Index()
        {
            return View();
        }

        #region STATIC
        public static void RemoverCandidatoAula(int idCandidato, UnitOfWork unit)
        {
            try
            {
                unit.CandidatoAulaRepository.Remover(idCandidato);
            }
            catch (Exception e)
            {
                throw new Exception("Não foi possível remover a lista de presença do candidato " 
                                   + idCandidato + ": " + e.Message);
            }
        }
        #endregion


        #region OVERRIDE
        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
        #endregion
    }
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Controllers/CursoController.cs
using Fiap.RH.Sistema.Contratacao.Dominio;
using Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels;
using Fiap.RH.Sistema.Contratacao.Persistencia.UnitsOfWork;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Fiap.RH.Sistema.Contratacao.MCV.Web.Controllers
{
    public class CursoController : Controller
    {
        #region FIELDS
        private UnitOfWork _unit = new UnitOfWork();
        #endregion


        #region GET
        [HttpGet]
        public ActionResult Cadastrar(string mensagem)
        {
            var cursoViewModel = new CursoViewModel()
            {
                Mensagem = mensagem
            };
            return View(cursoViewModel);
        }

        [HttpGet]
        public ActionResult Listar()
        {
            var cursoViewModel = new CursoViewModel();
            try
            {
                cursoViewModel.Cursos = _unit.CursoRepository.Listar();
            }
            catch (Exception e)
            {
                cursoViewModel.Mensagem = "Erro ao buscar os cursos no banco de dados: " + e.Message;
            }

            return View(cursoViewModel);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            Curso curso = null;
            var cursoViewModel = new CursoViewModel();

            try
            {
                curso = _unit.CursoRepository.BuscarPorId(id);
                cursoViewModel.Id = curso.Id;
                cursoViewModel.Nome = curso.Nome;
            }
            catch (Exception e)
            {
                cursoViewModel.Mensagem = "Erro ao buscar o curso no banco de dados para editar: " + e.Message;
            }

            return View(cursoViewModel);
        }
        #endregion


        #region POST
        [HttpPost]
        public ActionResult Cadastrar(CursoViewModel cursoViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (IsCursoDuplicado(cursoViewModel))
                    {
                        cursoViewModel.Mensagem = "Já existe um curso com este nome!";
                        return View(cursoViewModel);
                    }

                    var curso = new Curso()
                    {
                        Nome = cursoViewModel.Nome
                    };

                    _unit.CursoRepository.Cadastrar(curso);
                    _unit.Save();
                }
                catch (Exception e)
                {
                    cursoViewModel.Mensagem = "Erro ao cadastrar curso: " + e.Message;
                    return View(cursoViewModel);
                }
            }
            else return View(cursoViewModel);

            return RedirectToAction("Listar");
        }

        [HttpPost]
        public JsonResult Remover(int id)
        {
            try
            {
                _unit.CursoRepository.Remover(id);
                _unit.Save();
            }
            catch (Exception e)
            {
                return Json(new { status = false, mensagem = "Existe algum candidato associado a este curso?"
                                                           + " Se sim deve trocar antes de remover."
                                                           + " Erro ao remover: " + e.Message });
            }
            return Json(new { status = true });
        }

        [HttpPost]
        public ActionResult Editar(CursoViewModel cursoViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (IsCursoDuplicado(cursoViewModel))
                    {
                        cursoViewModel.Mensagem = "Já existe um curso com este nome!";
                        return View(cursoViewModel);
                    }

                    var curso = _unit.CursoRepository.BuscarPorId(cursoViewModel.Id);
                    curso.Nome = cursoViewModel.Nome;
                    _unit.CursoRepository.Editar(curso);
                    _unit.Save();
                }
                catch (Exception e)
                {
                    cursoViewModel.Mensagem = "Erro ao editar o curso: " + e.Message;
                    return View(cursoViewModel);
                }
            }
            else return View(cursoViewModel);

            return RedirectToAction("Listar");
        }
        #endregion


        #region PRIVATE
        public bool IsCursoDuplicado(CursoViewModel cursoViewModel)
        {
            var cursos = _unit.CursoRepository.BuscarPor(c => c.Nome == cursoViewModel.Nome);
            if (cursos.Any() && !(cursos.First().Id == cursoViewModel.Id)) return true;
            return false;
        }
        #endregion


        #region OVERRIDE
        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
        #endregion
    }
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Controllers/PerfilController.cs
using Fiap.RH.Sistema.Contratacao.Dominio;
using Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels;
using Fiap.RH.Sistema.Contratacao.Persistencia.UnitsOfWork;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Fiap.RH.Sistema.Contratacao.MCV.Web.Controllers
{
    public class PerfilController : Controller
    {
        #region FIELDS
        private UnitOfWork _unit = new UnitOfWork();
        #endregion


        #region GET
        [HttpGet]
        public ActionResult Cadastrar(string mensagem)
        {
            var perfilViewModel = new PerfilViewModel()
            {
                Mensagem = mensagem
            };
            return View(perfilViewModel);
        }

        [HttpGet]
        public ActionResult Listar()
        {
            var perfilViewModel = new PerfilViewModel();
            try
            {
                perfilViewModel.Perfis = _unit.PerfilProfissionalRepository.Listar();
            }
            catch (Exception e)
            {
                perfilViewModel.Mensagem = "Erro ao buscar os perfis no banco de dados: " + e.Message;
            }
            return View(perfilViewModel);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            PerfilProfissional perfil = null;
            var perfilViewModel = new PerfilViewModel();

            try
            {
                perfil = _unit.PerfilProfissionalRepository.BuscarPorId(id);
                perfilViewModel.Id = perfil.Id;
                perfilViewModel.Descricao = perfil.Descricao;
            }
            catch (Exception e)
            {
                perfilViewModel.Mensagem = "Erro ao buscar o perfil no banco de dados para editar: " + e.Message;
            }

            return View(perfilViewModel);
        }
        #endregion


        #region POST
        [HttpPost]
        public ActionResult Cadastrar(PerfilViewModel perfilViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (IsPerfilDuplicado(perfilViewModel))
                    {
                        perfilViewModel.Mensagem = "Já existe um perfil com este nome!";
                        return View(perfilViewModel);
                    }

                    var perfil = new PerfilProfissional()
                    {
                        Descricao = perfilViewModel.Descricao
                    };

                    _unit.PerfilProfissionalRepository.Cadastrar(perfil);
                    _unit.Save();
                }
                catch (Exception e)
                {
                    perfilViewModel.Mensagem = "Erro ao cadastrar perfil: " + e.Message;
                    return View(perfilViewModel);
                }
            }
            else return View(perfilViewModel);

            return RedirectToAction("Listar");
        }

        [HttpPost]
        public JsonResult Remover(int id)
        {
            try
            {
                _unit.PerfilProfissionalRepository.Remover(id);
                _unit.Save();
            }
            catch (Exception e)
            {
                return Json(new
                {
                    status = false,
                    mensagem = "Existe algum candidato associado a este perfil?"
                               + " Se sim deve trocar antes de remover."
                               + " Erro ao remover: " + e.Message
                });
            }
            return Json(new { status = true });
        }

        [HttpPost]
        public ActionResult Editar(PerfilViewModel perfilViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (IsPerfilDuplicado(perfilViewModel))
                    {
                        perfilViewModel.Mensagem = "Já existe um perfil com este nome!";
                        return View(perfilViewModel);
                    }

                    var perfil = _unit.PerfilProfissionalRepository.BuscarPorId(perfilViewModel.Id);
                    perfil.Descricao = perfilViewModel.Descricao;
                    _unit.PerfilProfissionalRepository.Editar(perfil);
                    _unit.Save();
                }
                catch (Exception e)
                {
                    perfilViewModel.Mensagem = "Erro ao editar o perfil: " + e.Message;
                    return View(perfilViewModel);
                }
            }
            else return View(perfilViewModel);

            return RedirectToAction("Listar");
        }
        #endregion


        #region PRIVATE
        public bool IsPerfilDuplicado(PerfilViewModel perfilViewModel)
        {
            var perfis = _unit.PerfilProfissionalRepository.BuscarPor(p => p.Descricao == perfilViewModel.Descricao);
            if (perfis.Any() && !(perfis.First().Id == perfilViewModel.Id)) return true;
            return false;
        }
        #endregion


        #region OVERRIDE
        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
        #endregion
    }
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Controllers/UnidadeController.cs
using Fiap.RH.Sistema.Contratacao.Dominio;
using Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels;
using Fiap.RH.Sistema.Contratacao.Persistencia.UnitsOfWork;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Fiap.RH.Sistema.Contratacao.MCV.Web.Controllers
{
    public class UnidadeController : Controller
    {
        #region FIELDS
        private UnitOfWork _unit = new UnitOfWork();
        #endregion


        #region GET
        [HttpGet]
        public ActionResult Cadastrar(string mensagem)
        {
            var unidadeViewModel = new UnidadeViewModel()
            {
                Mensagem = mensagem
            };
            return View(unidadeViewModel);
        }

        [HttpGet]
        public ActionResult Listar()
        {
            var unidadeViewModel = new UnidadeViewModel();
            try
            {
                unidadeViewModel.Unidades = _unit.UnidadeRepository.Listar();
            }
            catch (Exception e)
            {
                unidadeViewModel.Mensagem = "Erro ao buscar as unidades no banco de dados: " + e.Message;
            }
            return View(unidadeViewModel);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            Unidade unidade = null;
            var unidadeViewModel = new UnidadeViewModel();

            try
            {
                unidade = _unit.UnidadeRepository.BuscarPorId(id);
                unidadeViewModel.Id = unidade.Id;
                unidadeViewModel.Nome = unidade.Nome;
            }
            catch (Exception e)
            {
                unidadeViewModel.Mensagem = "Erro ao buscar a unidade no banco de dados para editar: " + e.Message;
            }

            return View(unidadeViewModel);
        }
        #endregion


        #region POST
        [HttpPost]
        public ActionResult Cadastrar(UnidadeViewModel unidadeViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (IsUnidadeDuplicada(unidadeViewModel))
                    {
                        unidadeViewModel.Mensagem = "Já existe uma unidade com este nome!";
                        return View(unidadeViewModel);
                    }

                    var unidade = new Unidade()
                    {
                        Nome = unidadeViewModel.Nome
                    };

                    _unit.UnidadeRepository.Cadastrar(unidade);
                    _unit.Save();
                }
                catch (Exception e)
                {
                    unidadeViewModel.Mensagem = "Erro ao cadastrar unidade: " + e.Message;
                    return View(unidadeViewModel);
                }
            }
            else return View(unidadeViewModel);

            return RedirectToAction("Listar");
        }

        [HttpPost]
        public JsonResult Remover(int id)
        {
            try
            {
                _unit.UnidadeRepository.Remover(id);
                _unit.Save();
            }
            catch (Exception e)
            {
                return Json(new
                {
                    status = false,
                    mensagem = "Existe algum candidato associado a esta unidade?"
                               + " Se sim deve trocar antes de remover."
                               + " Erro ao remover: " + e.Message
                });
            }
            return Json(new { status = true });
        }

        [HttpPost]
        public ActionResult Editar(UnidadeViewModel unidadeViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (IsUnidadeDuplicada(unidadeViewModel))
                    {
                        unidadeViewModel.Mensagem = "Já existe uma unidade com este nome!";
                        return View(unidadeViewModel);
                    }

                    var unidade = _unit.UnidadeRepository.BuscarPorId(unidadeViewModel.Id);
                    unidade.Nome = unidadeViewModel.Nome;
                    _unit.UnidadeRepository.Editar(unidade);
                    _unit.Save();
                }
                catch (Exception e)
                {
                    unidadeViewModel.Mensagem = "Erro ao editar a unidade: " + e.Message;
                    return View(unidadeViewModel);
                }
            }
            else return View(unidadeViewModel);

            return RedirectToAction("Listar");
        }
        #endregion


        #region PRIVATE
        public bool IsUnidadeDuplicada(UnidadeViewModel unidadeViewModel)
        {
            var unidades = _unit.UnidadeRepository.BuscarPor(a => a.Nome == unidadeViewModel.Nome);
            if (unidades.Any() && !(unidades.First().Id == unidadeViewModel.Id)) return true;
            return false;
        }
        #endregion


        #region OVERRIDE
        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
        #endregion
    }
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>FIAP - @ViewBag.Title</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/vendor.css">
    <link rel="stylesheet" type="text/css" href="~/Content/flat-admin.css">
    <link rel="stylesheet" type="text/css" href="~/Content/meu.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    

</head>
<body>
    <div class="app app-default">
        <aside class="app-sidebar" id="sidebar" style="position:fixed;">
            <div class="sidebar-header">
                <a class="sidebar-brand" href="#"><img src="~/Content/images/FiapLogo.png" /></a>

                <button type="button" class="sidebar-toggle">
                    <i class="fa fa-times"></i>
                </button>
            </div>
            <div class="sidebar-menu">
                <ul class="sidebar-nav">
                    <!--Dados gerais-->
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <div class="icon">
                                <i class="fa fa-tasks" aria-hidden="true"></i>
                            </div>
                            <div class="title">Dados Gerais</div>
                        </a>
                        <div class="dropdown-menu">
                            <ul>
                                <li class="section"><i class="fa fa-file-o" aria-hidden="true"></i> Dados Gerais</li>
                                <li>@Html.ActionLink("Cursos", "Listar", "Curso")</li>
                                <li>@Html.ActionLink("Habilidades", "Listar", "Habilidade")</li>
                                <li>@Html.ActionLink("Perfil Profissional", "Listar", "Perfil")</li>
                                <li>@Html.ActionLink("Unidades", "Listar", "Unidade")</li>
                            </ul>
                        </div>
                    </li>
                    <!--Fábricas-->
                    <li>
                        <a href='@Url.Action("Listar", "Fabrica")'>
                            <div class="icon">
                                <i class="fa fa-cubes" aria-hidden="true"></i>
                            </div>
                            <div class="title">
                                Fábrica
                            </div>
                        </a>
                    </li>
                    <!--Candidatos-->
                    <li>
                        <a href='@Url.Action("Listar", "Candidato")'>
                            <div class="icon">
                                <i class="fa fa-group" aria-hidden="true"></i>
                            </div>
                            <div class="title">Candidatos</div>
                        </a>
                    </li>
                    <!--Aulas-->
                    <li>
                        <a href='@Url.Action("Listar", "Aula")'>
                            <div class="icon">
                                <i class="fa fa-calendar-o" aria-hidden="true"></i>
                            </div>
                            <div class="title">Aulas</div>
                        </a>
                    </li>
                </ul>
            </div>
            <!--Footer Sidebar-->
            <div class="sidebar-footer">
            </div>
        </aside>
        <script type="text/ng-template" id="sidebar-dropdown.tpl.html">
            <div class="dropdown-background">
                <div class="bg"></div>
            </div>
            <div class="dropdown-container">
                {{list}}
            </div>
        </script>
        <div class="app-container">
            <nav class="navbar navbar-default" id="navbar">
                <div class="container-fluid">
                    <div class="navbar-collapse collapse in">
                        <ul class="nav navbar-nav navbar-mobile">
                            <li>
                                <button type="button" class="sidebar-toggle">
                                    <i class="fa fa-bars"></i>
                                </button>
                            </li>
                            <li class="logo">
                                <a class="navbar-brand" href="#"><img src="~/Content/images/FiapLogo.png" /></a>
                            </li>
                            <li>
                                <button type="button" class="navbar-toggle">
                                    <i class="fa fa-user"></i>
                                </button>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-left">
                            <li class="navbar-title"><span class="highlight">@ViewBag.TitleMenu</span></li>
                            <li class="navbar-search hidden-sm">
                                <input id="search" type="text" placeholder="Search..">
                                <button class="btn-search"><i class="fa fa-search"></i></button>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown profile">
                                <a href="/html/pages/profile.html" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-user"></i>
                                    <div class="title">Profile</div>
                                </a>
                                <div class="dropdown-menu">
                                    <div class="profile-info">
                                        <h4 class="username">Scott White</h4>
                                    </div>
                                    <ul class="action">
                                        <li>
                                            <a href="#">
                                                Setting
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                Logout
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <div class="row">
                @RenderBody()
            </div>
        </div>
    </div>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.12/datatables.min.js"></script>
    <script type="text/javascript" src="~/Scripts/vendor.js"></script>
    
    <script type="text/javascript" src="~/Scripts/app.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    @RenderSection("scripts", false)
</body>
</html>