Fiap.RH.Sistema.Contratacao.MCV.Web/ViewModels/HabilidadeViewModel.cs
using Fiap.RH.Sistema.Contratacao.Dominio;
using System.Collections.Generic;

namespace Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels
{
    public class HabilidadeViewModel
    {
        #region VIEW PROPS
        public string Mensagem { get; set; }
        #endregion

        #region MODEL PROPS
        public int Id { get; set; }

        public string Nome { get; set; }
        #endregion

        #region MODEL COLLECTION
        public ICollection<Habilidade> Habilidades { get; set; }
        #endregion
    }
}

Fiap.RH.Sistema.Contratacao.MCV.Web/ViewModels/RelatorioViewModel.cs
using Fiap.RH.Sistema.Contratacao.Dominio;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels
{
    public class RelatorioViewModel
    {
        #region VIEW PROPS
        public string Mensagem { get; set; }
        public SelectList Habilidades { get; set; }
        #endregion


        #region MODEL PROPS
        public int Id { get; set; }
        public int Faltas { get; set; }
        public int AderenciaComportamental { get; set; }
        public decimal DesempenhoNota { get; set; }
        public string Status { get; set; }
        public Candidato Candidato { get; set; }
        public Login Login { get; set; }
        #endregion


        #region PARTIAL
        [Required(ErrorMessage = "Selecione uma habilidade")]
        public int NovaHabilidadeId { get; set; }
        #endregion


        #region MODEL COLLECTION
        public ICollection<RelatorioHabilidade> HabilidadesDoCandidato { get; set; }
        #endregion
    }
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Controllers/HabilidadeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Fiap.RH.Sistema.Contratacao.Persistencia.UnitsOfWork;
using Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels;
using Fiap.RH.Sistema.Contratacao.Dominio;


namespace Fiap.RH.Sistema.Contratacao.MCV.Web.Controllers
{
    public class HabilidadeController : Controller
    {
        #region FIELDS
        private UnitOfWork _unit = new UnitOfWork();
        #endregion


        #region GET
        [HttpGet]
        public ActionResult Cadastrar(string mensagem)
        {
            var habilidadeViewModel = new HabilidadeViewModel()
            {
                Mensagem = mensagem
            };
            return View(habilidadeViewModel);
        }

        [HttpGet]
        public ActionResult Listar()
        {
            var habilidadeViewModel = new HabilidadeViewModel();
            try
            {
                habilidadeViewModel.Habilidades = _unit.HabilidadeRepository.Listar();
            }
            catch (Exception e)
            {
                habilidadeViewModel.Mensagem = "Erro ao buscar as habilidades no banco de dados: " + e.Message;
            }
            return View(habilidadeViewModel);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            Habilidade habilidade = null;
            var habilidadeViewModel = new HabilidadeViewModel();

            try
            {
                habilidade = _unit.HabilidadeRepository.BuscarPorId(id);
                habilidadeViewModel.Id = habilidade.Id;
                habilidadeViewModel.Nome = habilidade.Nome;
            }
            catch (Exception e)
            {
                habilidadeViewModel.Mensagem = "Erro ao buscar a habilidade no banco de dados para editar: " + e.Message;
            }

            return View(habilidadeViewModel);
        }
        #endregion


        #region POST
        [HttpPost]
        public ActionResult Cadastrar(HabilidadeViewModel habilidadeViewModel)
        {
            if (ModelState.IsValid)
            {
               try
               {
                    if (IsHabilidadeDuplicada(habilidadeViewModel))
                    {
                        habilidadeViewModel.Mensagem = "Já existe uma habilidade com este nome!";
                        return View(habilidadeViewModel);
                    }

                    var habilidade = new Habilidade()
                    {
                        Nome = habilidadeViewModel.Nome
                    };

                    _unit.HabilidadeRepository.Cadastrar(habilidade);
                    _unit.Save();
               }
               catch (Exception e)
               {
                    habilidadeViewModel.Mensagem = "Erro ao cadastrar habilidade: " + e.Message;
                    return View(habilidadeViewModel);
               }
            }
            else return View(habilidadeViewModel);

            return RedirectToAction("Listar");
        }

        [HttpPost]
        public JsonResult Remover(int id)
        {
            try
            {
                _unit.HabilidadeRepository.Remover(id);
                _unit.Save();
            }
            catch (Exception e)
            {
                return Json(new
                {
                    status = false,
                    mensagem = "Existe algum relatório de candidato associado a esta habilidade?"
                               + " Se sim deve trocar antes de remover."
                               + " Erro ao remover: " + e.Message
                });
            }
            return Json(new { status = true });
        }

        [HttpPost]
        public ActionResult Editar(HabilidadeViewModel habilidadeViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (IsHabilidadeDuplicada(habilidadeViewModel))
                    {
                        habilidadeViewModel.Mensagem = "Já existe uma habilidade com este nome!";
                        return View(habilidadeViewModel);
                    }

                    var habilidade = _unit.HabilidadeRepository.BuscarPorId(habilidadeViewModel.Id);
                    habilidade.Nome = habilidadeViewModel.Nome;
                    _unit.HabilidadeRepository.Editar(habilidade);
                    _unit.Save();
                }
                catch (Exception e)
                {
                    habilidadeViewModel.Mensagem = "Erro ao editar a habilidade: " + e.Message;
                    return View(habilidadeViewModel);
                }
            }
            else return View(habilidadeViewModel);

            return RedirectToAction("Listar");
        }
        #endregion


        #region PRIVATE
        public bool IsHabilidadeDuplicada(HabilidadeViewModel habilidadeViewModel)
        {
            var habilidades = _unit.HabilidadeRepository.BuscarPor(a => a.Nome == habilidadeViewModel.Nome);
            if (habilidades.Any() && !(habilidades.First().Id == habilidadeViewModel.Id)) return true;
            return false;
        }
        #endregion


        #region OVERRIDE
        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
        #endregion
    }
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Controllers/RelatorioController.cs
using Fiap.RH.Sistema.Contratacao.Dominio;
using Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels;
using Fiap.RH.Sistema.Contratacao.Persistencia.UnitsOfWork;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Fiap.RH.Sistema.Contratacao.MCV.Web.Controllers
{
    public class RelatorioController : Controller
    {
        #region FIELDS
        private UnitOfWork _unit = new UnitOfWork();
        #endregion


        #region GET
        [HttpGet]
        public ActionResult Gerar(int id, string mensagem)
        {
            Relatorio relatorio = null;
            try
            {
                relatorio = _unit.RelatorioRepository.BuscarPorId(id);
                relatorio.Faltas = CalculaFaltas(id);
                _unit.Save(); //atualiza as faltas no sistema, apesar de sempre calcular para exibir
            }
            catch (Exception e)
            {
                ViewBag.Mensagem = "Erro ao gerar relatório: " + e.Message;
                return View("Gerar");
            }

            ViewBag.Mensagem = mensagem;
            return View(relatorio);
        }

        [HttpGet]
        public ActionResult Editar(int id, string mensagem)
        {
            Relatorio relatorio = null;
            RelatorioViewModel relatorioViewModel = new RelatorioViewModel();

            try
            {
                relatorio = _unit.RelatorioRepository.BuscarPorId(id);
                relatorioViewModel.Id = relatorio.Id;
                relatorioViewModel.AderenciaComportamental = relatorio.AderenciaComportamental;
                relatorioViewModel.Candidato = relatorio.Candidato;
                relatorioViewModel.DesempenhoNota = relatorio.DesempenhoNota;
                relatorioViewModel.HabilidadesDoCandidato = relatorio.RelatorioHabilidades;

                var habilidades = _unit.HabilidadeRepository.Listar();
                relatorioViewModel.Habilidades = new SelectList(habilidades, "Id", "Nome");
            }
            catch (Exception e)
            {
                relatorioViewModel.Mensagem = "Erro ao gerar relatório para alterações: " + e.Message;
            }

            relatorioViewModel.Mensagem = mensagem;
            return View(relatorioViewModel);
        }

        [HttpGet]
        public ActionResult AdicionarHabilidade(int id)
        {
            RelatorioViewModel relatorioViewModel = new RelatorioViewModel();
            try
            {
                ICollection<Habilidade> habilidades = _unit.HabilidadeRepository.Listar();
                relatorioViewModel.Habilidades = new SelectList(habilidades, "Id", "Nome");
                relatorioViewModel.Id = id;
                relatorioViewModel.Candidato = _unit.CandidatoRepository.BuscarPorId(id);
            }
            catch (Exception e)
            {
                relatorioViewModel.Mensagem = "Erro ao buscar as habilidades no banco de dados para seleção: " + e.Message;
            }
            return View(relatorioViewModel);
        }
        #endregion


        #region POST
        [HttpPost]
        public ActionResult Editar(RelatorioViewModel relatorioViewModel)
        {
            Relatorio relatorio = null;
            try
            {
                relatorio = _unit.RelatorioRepository.BuscarPorId(relatorioViewModel.Id);
                relatorio.AderenciaComportamental = relatorioViewModel.AderenciaComportamental;
                relatorio.DesempenhoNota = relatorioViewModel.DesempenhoNota;
                _unit.RelatorioRepository.Editar(relatorio);
                _unit.Save();
            }
            catch (Exception e)
            {
                relatorioViewModel.Mensagem = "Erro ao salvar as alterações do relatório: " + e.Message;
                return View(relatorioViewModel);
            }

            return RedirectToAction("Gerar", new { id = relatorio.Id, mensagem = "Relatório alterado com sucesso!"});
        }

        
        [HttpPost]
        public ActionResult AdicionarHabilidade(RelatorioViewModel relatorioViewModel)
        {
            if (ModelState.IsValidField("NovaHabilidadeId"))
            {
                RelatorioHabilidade novaHabilidade = new RelatorioHabilidade()
                {
                    IdRelatorio = relatorioViewModel.Id,
                    IdHabilidade = relatorioViewModel.NovaHabilidadeId,
                };

                try
                {
                    _unit.RelatorioHabilidadeRepository.Cadastrar(novaHabilidade);
                    _unit.Save();
                }
                catch (Exception e)
                {
                    relatorioViewModel.Mensagem = "Erro ao adicionar nova habilidade: " + e.Message;
                    return View(relatorioViewModel);
                }
            }
            else return View(relatorioViewModel);

            return RedirectToAction("Editar", new { id = relatorioViewModel.Id, mensagem = "Habilidade adicionada com sucesso!" });
        }

        [HttpPost]
        public JsonResult RemoverHabilidade(int id)
        {
            try
            {
                _unit.RelatorioHabilidadeRepository.RemoverPelaOrdem(id);
                _unit.Save();
            }
            catch(Exception e)
            {
                return Json(new { status = false, mensagem = "Erro ao remover a habilidade do relatório: " + e.Message });
            }
            return Json(new { status = true });
        }

        [HttpPost]
        public JsonResult AtualizarHabilidade(int id, int idHabilidade)
        {
            try
            {
                RelatorioHabilidade relatorioHabilidade = _unit.RelatorioHabilidadeRepository.BuscaPelaOrdem(id);
                relatorioHabilidade.IdHabilidade = idHabilidade;
                _unit.RelatorioHabilidadeRepository.Editar(relatorioHabilidade);
                _unit.Save();
            }
            catch (Exception e)
            {
                return Json(new { status = false, mensagem = "Erro ao atualizar a habilidade do relatório: " + e.Message });
            }
            return Json(new { status = true });
        }

        [HttpPost]
        public ActionResult Aprovar(int id)
        {
            Relatorio relatorio = null;
            try
            {
                relatorio = _unit.RelatorioRepository.BuscarPorId(id);
                relatorio.Status = "Aprovado";
                relatorio.LoginId = 1; //TODO !! recuperar id do login de usuário!
                _unit.RelatorioRepository.Editar(relatorio);
                _unit.Save();
            }
            catch (Exception e)
            {
                return RedirectToAction("Gerar", new { id = id, mensagem = "Erro ao aprovar candidato: " + e.Message });
            }

            return RedirectToAction("Gerar", new { id = id, mensagem = "Candidato aprovado com sucesso!"});
        }

        [HttpPost]
        public ActionResult Reprovar(int id)
        {
            Relatorio relatorio = null;
            try
            {
                relatorio = _unit.RelatorioRepository.BuscarPorId(id);
                relatorio.Status = "Reprovado";
                relatorio.LoginId = 1; //TODO !! recuperar id do login de usuário!
                _unit.RelatorioRepository.Editar(relatorio);
                _unit.Save();
            }
            catch (Exception e)
            {
                return RedirectToAction("Gerar", new { id = id, mensagem = "Erro ao reprovar candidato: " + e.Message });
            }

            return RedirectToAction("Gerar", new { id = id, mensagem = "Candidato foi corretamente reprovado" });
        }
        #endregion


        #region PRIVATE
        private int CalculaFaltas(int id)
        {
            ICollection<CandidatoAula> aulas = null;
            try
            {
                aulas = _unit.CandidatoAulaRepository.BuscarPor(ca => ca.IdCandidato == id);
            }
            catch (Exception e)
            {
                throw new Exception("Não foi possível encontrar as aulas que o candidato participou: " + e.Message);
            }
            int faltas = 0;
            foreach (var ca in aulas) if (ca.Presenca == false) faltas++;
            return faltas;
        }
        #endregion


        #region STATIC
        public static void Cadastrar(int id, UnitOfWork unit)
        {
            var relatorio = new Relatorio()
            {
                Id = id,
                AderenciaComportamental = 0,
                DesempenhoNota = 0,
                Faltas = 0,
                Status = "Indefinido"
            };

            try
            {
                Login login = RecuperaLoginDoAdm(unit);
                relatorio.Id = login.Id;
                unit.RelatorioRepository.Cadastrar(relatorio);
            }
            catch (Exception e)
            {
                throw new Exception("Não foi possível criar o relatório individual do candidato: " + e.Message);
            }
        }

        public static Login RecuperaLoginDoAdm(UnitOfWork unit)
        {
            var logins = unit.LoginRepository.BuscarPor(l => l.Nome == "Adm");
            Login login = null;
            if (logins.GetEnumerator().MoveNext())
            {
                login = logins.GetEnumerator().Current;
            }
            else
            {
                login = CriaLoginDoAdm(unit);
            }

            return login;
        }

        public static Login CriaLoginDoAdm(UnitOfWork unit)
        {
            Login login = new Login()
            {
                Nome = "Adm",
                Email = "adm@fiap.com.br",
                Senha = "adm"
            };
            unit.LoginRepository.Cadastrar(login);
            return login;
        }

        public static void Remover(int id, UnitOfWork unit)
        {
            try
            {
                unit.RelatorioRepository.Remover(id);
            }
            catch (Exception e)

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Relatorio/AdicionarHabilidade.cshtml
@model Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels.RelatorioViewModel

@{
    ViewBag.Title = "AdicionarHabilidade";
}

<h1>@Model.Candidato.Nome</h1>

<h2>Adicionar habilidade ao relatório</h2>

@using(Html.BeginForm("AdicionarHabilidade", "Relatorio", FormMethod.Post, new { @class = "form", id = "adicionarHabilidade" }))
{
    @Html.HiddenFor(r => r.Id)
    
    @Html.LabelFor(r => r.NovaHabilidadeId, new { @class = "control-label col-lg-2" })
    @Html.DropDownListFor(r => r.NovaHabilidadeId, Model.Habilidades, "Selecione uma habilidade", new { @class = "form-control"})
    @Html.ValidationMessageFor(r => r.NovaHabilidadeId, "", new { @class = "text-warning"})

    @Helper.Submit("Adicionar", "btn btn-primary")
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Relatorio/Editar.cshtml
@model Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels.RelatorioViewModel

@{
    ViewBag.Title = "Editar";
}

@Helper.Message(Model.Mensagem, "alert alert-warning")
@Helper.Message(ViewBag.Mensagem, "alert alert-warning")

<h1>@Model.Candidato.Nome</h1>

<h2>Habilidades</h2>

@Html.Partial("_habilidades")

<hr />

@using(Html.BeginForm("Editar", "Relatorio", FormMethod.Post, new { @class = "form", id = "formularioRelatorio" }))
{
    @Html.HiddenFor(r => r.Id)
    @Html.Partial("_formulario")
    <div class="col-lg-3"></div>
    @Helper.Submit("Concluir", "btn btn-primary")
}

@section scripts
{
    <script src="~/Scripts/ViewModels/relatorio.js"></script>
}

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Relatorio/Gerar.cshtml
@model Fiap.RH.Sistema.Contratacao.Dominio.Relatorio

@{
    ViewBag.Title = "Gerar";
}

@Helper.Message(ViewBag.Mensagem, "alert alert-warning")

<h1>@Model.Candidato.Nome</h1>

<section id="relatorio">
    <div class="row">
        <div class="col-lg-3">Número do Candidato</div>
        <div class="col-lg-3">@Model.Candidato.Id</div>
    </div>
    <div class="row">
        <div class="col-lg-3">Curso</div>
        <div class="col-lg-3">@Model.Candidato.Curso.Nome</div>
    </div>
    <div class="row">
        <div class="col-lg-3">Unidade</div>
        <div class="col-lg-3">@Model.Candidato.Unidade.Nome</div>
    </div>
    <div class="row">
        <div class="col-lg-3">Total de Faltas</div>
        <div class="col-lg-3">@Model.Faltas</div>
    </div>
    <div class="row">
        <div class="col-lg-3">Aderência Comportamental</div>
        <div class="col-lg-3">@Model.AderenciaComportamental%</div>
    </div>
    <div class="row">
        <div class="col-lg-3">Perfil Profissional</div>
        <div class="col-lg-3">@Model.Candidato.PerfilProfissional.Descricao</div>
    </div>
    <div class="row">
        <div class="col-lg-3">Desempenho da Nota</div>
        <div class="col-lg-3">@Model.DesempenhoNota</div>
    </div>

    <hr />

    <!-- Habilidades Mostrar no máximo 5! -->
    <div class="row">
        <div class="col-lg-3">Habilidades Principais</div>
        <div class="col-lg-3">
            @if (Model.RelatorioHabilidades.Count > 5)
            {
                for (int i = 0; i < 5; i++)
                {
                    <div class="row">@Model.RelatorioHabilidades.ElementAt(@i).Habilidade.Nome</div>
                }
            }
            else
            {
                foreach (var h in Model.RelatorioHabilidades)
                {
                    <div class="row">@h.Habilidade.Nome</div>
                }
            }
        </div>
    </div>

    <hr />

    <!-- Status -->
    <div class="row">
        <div class="col-lg-3">Status</div>
        <div class="col-lg-2">@Model.Status</div>
        <div class="col-lg-3">Status registrado por: @Model.Login.Nome, @Model.Login.Email</div>
        <div class="col-lg-4">
            @if (Model.Status == "Aprovado")
            {
                using (Html.BeginForm("Reprovar", "Relatorio", FormMethod.Post, new { @class = "form form-horizontal", id = "formularioReprovar" }))
                {
                    @Html.HiddenFor(r => r.Id)
                    @Helper.Submit("Alterar para Reprovado", "btn btn-danger")
                }
            }
            else if (Model.Status == "Reprovado")
            {
                using (Html.BeginForm("Aprovar", "Relatorio", FormMethod.Post, new { @class = "form", id = "formularioAprovar" }))
                {
                    @Html.HiddenFor(r => r.Id)
                    @Helper.Submit("Alterar para Aprovado", "btn btn-primary")
                }
            }
            else
            {
                <div class="col-lg-6">
                    @using (Html.BeginForm("Aprovar", "Relatorio", FormMethod.Post, new { @class = "form", id = "formularioAprovar" }))
                    {
                        @Html.HiddenFor(r => r.Id)
                        @Helper.Submit("Aprovar", "btn btn-lg btn-primary")
                    }
                </div>
                <div class="col-lg-6">
                    @using (Html.BeginForm("Reprovar", "Relatorio", FormMethod.Post, new { @class = "form", id = "formularioReprovar" }))
                    {
                        @Html.HiddenFor(r => r.Id)
                        @Helper.Submit("Reprovar", "btn btn-lg btn-danger")
                    }
                </div>
            }
        </div>
    </div>

    <div class="row">
        <a class="btn btn-primary" href="/Relatorio/Editar/@Model.Id">Editar Relatório</a>
    </div>
</section>

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Relatorio/_formulario.cshtml
@model Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels.RelatorioViewModel

<div class="form-group">
    @Html.LabelFor(r => r.AderenciaComportamental, new { @class = "control-label lead col-lg-3" })
    @Html.TextBoxFor(r => r.AderenciaComportamental, new { @class = "form-control input-lg" })
    @Html.ValidationMessageFor(r => r.AderenciaComportamental, "", new { @class = "text-warning" })
</div>

<div class="form-group">
    @Html.LabelFor(r => r.DesempenhoNota, new { @class = "control-label lead col-lg-3" })
    @Html.TextBoxFor(r => r.DesempenhoNota, new { @class = "form-control input-lg" })
    @Html.ValidationMessageFor(r => r.DesempenhoNota, "", new { @class = "text-warning" })
</div>

Fiap.RH.Sistema.Contratacao.MCV.Web/Views/Relatorio/_habilidades.cshtml
@model Fiap.RH.Sistema.Contratacao.MCV.Web.ViewModels.RelatorioViewModel

<div class="row" id="habilidades">
    @{ int contador = 1; }
    @foreach(var h in Model.HabilidadesDoCandidato)
    {
        <div id="@h.IdOrdem" class="row">
            <div class="col-lg-3 text-right">
                <span class="lead">@contador</span>
            </div>
            <div class="col-lg-4">
                <select name="@h.IdOrdem" class = "form-control">
                    @foreach(var i in Model.Habilidades)
                    {
                        <option value="@i.Value" @(h.Habilidade.Nome == i.Text ? "selected='selected'" : "")>@i.Text</option>
                    }
                </select>
            </div>
            <div class="col-lg-3">
                <a class="btn btn-danger" onclick="removerHabilidade(@h.IdOrdem)"><i class="glyphicon glyphicon-trash"></i></a>
            </div>
        </div>
        contador++;
    }
</div>
<div class="row">
    <div class="col-lg-3"></div>
    <a class="btn btn-primary" href="/Relatorio/AdicionarHabilidade/@Model.Id"><i class="glyphicon glyphicon-plus"></i></a>
</div>